// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrilhasBrasil.API.Data;

#nullable disable

namespace TrilhasBrasil.API.Migrations
{
    [DbContext(typeof(TrilhasBrasilDbContext))]
    partial class TrilhasBrasilDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrilhasBrasil.API.Models.Dificuldade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dificuldades");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d729fe9-54e6-4482-a88e-59d6e6921f00"),
                            Nome = "Fácil"
                        },
                        new
                        {
                            Id = new Guid("472f64f1-d96e-4a61-ba3b-b7899657ed57"),
                            Nome = "Médio"
                        },
                        new
                        {
                            Id = new Guid("8d0fb2f1-20b7-4f78-9e28-67acf50a41d7"),
                            Nome = "Difícil"
                        });
                });

            modelBuilder.Entity("TrilhasBrasil.API.Models.Estado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EstadoImagemURl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50bb6ee2-9569-4a40-bd85-2ca90a16678b"),
                            EstadoImagemURl = "https://media.gettyimages.com/id/560616935/pt/foto/portico-of-gramado-rio-grande-do-sul-brazil.jpg?s=2048x2048&w=gi&k=20&c=ExGu5ZKM5lWt0XsPuGQFwAQ2FCgjr7DLdqmSTI9RLRw=",
                            Nome = "Rio Grande do Sul",
                            Sigla = "RS"
                        },
                        new
                        {
                            Id = new Guid("72f01c89-0c88-4f78-b184-5735f0ea30d6"),
                            Nome = "Rio Grande do Norte",
                            Sigla = "RN"
                        },
                        new
                        {
                            Id = new Guid("94c09e4b-14b2-453e-9c9c-8e48ec3f9683"),
                            Nome = "Mato Grosso do Sul",
                            Sigla = "MS"
                        });
                });

            modelBuilder.Entity("TrilhasBrasil.API.Models.Trilha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DificuldadeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TamanhoKm")
                        .HasColumnType("float");

                    b.Property<string>("TrilhaImagemUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DificuldadeId");

                    b.HasIndex("EstadoId");

                    b.ToTable("Trilhas");
                });

            modelBuilder.Entity("TrilhasBrasil.API.Models.Trilha", b =>
                {
                    b.HasOne("TrilhasBrasil.API.Models.Dificuldade", "Dificuldade")
                        .WithMany()
                        .HasForeignKey("DificuldadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrilhasBrasil.API.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dificuldade");

                    b.Navigation("Estado");
                });
#pragma warning restore 612, 618
        }
    }
}
